use crate::model::CardKind;

#[derive(Debug, Clone, Copy)]
pub(crate) struct LayoutStyle {
    pub(crate) base_font_family: &'static str,
    pub(crate) name_font_family: &'static str,
    pub(crate) type_font_family: &'static str,
    pub(crate) effect_font_family: &'static str,
    pub(crate) stat_font_family: &'static str,
    pub(crate) link_font_family: &'static str,
    pub(crate) password_font_family: &'static str,
    pub(crate) name_top: u32,
    pub(crate) name_size: u32,
    pub(crate) type_top: u32,
    pub(crate) type_size: u32,
    pub(crate) effect_top: u32,
    pub(crate) effect_size: u32,
    pub(crate) effect_line_height: f32,
    pub(crate) description_size: u32,
    pub(crate) description_line_height: f32,
    pub(crate) pendulum_description_top: u32,
    pub(crate) pendulum_description_size: u32,
    pub(crate) title_max_width_with_attribute: u32,
    pub(crate) title_max_width_without_attribute: u32,
    pub(crate) body_max_width: u32,
    pub(crate) title_letter_spacing: f32,
    pub(crate) type_letter_spacing: f32,
    pub(crate) effect_letter_spacing: f32,
    pub(crate) description_letter_spacing: f32,
    pub(crate) name_x: u32,
    pub(crate) effect_x: u32,
    pub(crate) stat_atk_x: u32,
    pub(crate) stat_def_x: u32,
    pub(crate) stat_link_x: u32,
    pub(crate) stat_top: u32,
    pub(crate) stat_size: u32,
    pub(crate) link_top: u32,
    pub(crate) link_size: u32,
    pub(crate) stat_letter_spacing: f32,
}

pub(crate) fn layout_style(kind: CardKind, language: Option<&str>) -> LayoutStyle {
    match (kind, language.unwrap_or("sc")) {
        (CardKind::RushDuel, "jp") => LayoutStyle {
            base_font_family: "'rd-jp', 'Yu Gothic', sans-serif",
            name_font_family: "'rd-jp-name', 'rd-jp', 'Yu Gothic', sans-serif",
            type_font_family: "'rd-jp-effect', 'rd-jp', 'Yu Gothic', sans-serif",
            effect_font_family: "'rd-jp-effect', 'rd-jp', 'Yu Gothic', sans-serif",
            stat_font_family: "'rd-atk-def', 'Times New Roman', serif",
            link_font_family: "'rd-atk-def', 'Times New Roman', serif",
            password_font_family: "'rd-tip', 'rd-jp', monospace",
            name_top: 71,
            name_size: 92,
            type_top: 1476,
            type_size: 46,
            effect_top: 1476,
            effect_size: 46,
            effect_line_height: 1.15,
            description_size: 39,
            description_line_height: 1.39,
            pendulum_description_top: 1282,
            pendulum_description_size: 36,
            title_max_width_with_attribute: 1033,
            title_max_width_without_attribute: 1161,
            body_max_width: 1175,
            title_letter_spacing: 0.0,
            type_letter_spacing: 2.0,
            effect_letter_spacing: 2.0,
            description_letter_spacing: 0.0,
            name_x: 126,
            effect_x: 126,
            stat_atk_x: 1028,
            stat_def_x: 1306,
            stat_link_x: 1294,
            stat_top: 1804,
            stat_size: 54,
            link_top: 1820,
            link_size: 42,
            stat_letter_spacing: 1.5,
        },
        (CardKind::RushDuel, _) => LayoutStyle {
            base_font_family: "'rd-sc', 'Microsoft YaHei', sans-serif",
            name_font_family: "'rd-sc-name', 'rd-sc', 'Microsoft YaHei', sans-serif",
            type_font_family: "'rd-sc', 'Microsoft YaHei', sans-serif",
            effect_font_family: "'rd-sc', 'Microsoft YaHei', sans-serif",
            stat_font_family: "'rd-atk-def', 'Times New Roman', serif",
            link_font_family: "'rd-atk-def', 'Times New Roman', serif",
            password_font_family: "'rd-tip', 'rd-sc', monospace",
            name_top: 71,
            name_size: 92,
            type_top: 1476,
            type_size: 46,
            effect_top: 1476,
            effect_size: 46,
            effect_line_height: 1.15,
            description_size: 39,
            description_line_height: 1.39,
            pendulum_description_top: 1282,
            pendulum_description_size: 36,
            title_max_width_with_attribute: 1033,
            title_max_width_without_attribute: 1161,
            body_max_width: 1175,
            title_letter_spacing: 0.0,
            type_letter_spacing: 2.0,
            effect_letter_spacing: 2.0,
            description_letter_spacing: 0.0,
            name_x: 126,
            effect_x: 126,
            stat_atk_x: 1028,
            stat_def_x: 1306,
            stat_link_x: 1294,
            stat_top: 1804,
            stat_size: 54,
            link_top: 1820,
            link_size: 42,
            stat_letter_spacing: 1.5,
        },
        (_, "en") => LayoutStyle {
            base_font_family: "'ygo-en', 'Arial', sans-serif",
            name_font_family: "'ygo-en-name', 'ygo-en', 'Arial', sans-serif",
            type_font_family: "'ygo-en-race', 'ygo-en', 'Arial', sans-serif",
            effect_font_family: "'ygo-en-race', 'ygo-en', 'Arial', sans-serif",
            stat_font_family: "'ygo-atk-def', 'Times New Roman', serif",
            link_font_family: "'ygo-link', 'ygo-atk-def', 'Times New Roman', serif",
            password_font_family: "'ygo-password', 'ygo-en', monospace",
            name_top: 52,
            name_size: 158,
            type_top: 254,
            type_size: 74,
            effect_top: 1527,
            effect_size: 56,
            effect_line_height: 1.02,
            description_size: 42,
            description_line_height: 1.02,
            pendulum_description_top: 1282,
            pendulum_description_size: 42,
            title_max_width_with_attribute: 1033,
            title_max_width_without_attribute: 1161,
            body_max_width: 1175,
            title_letter_spacing: 1.0,
            type_letter_spacing: 1.0,
            effect_letter_spacing: 1.0,
            description_letter_spacing: 0.0,
            name_x: 124,
            effect_x: 118,
            stat_atk_x: 1010,
            stat_def_x: 1298,
            stat_link_x: 1288,
            stat_top: 1812,
            stat_size: 58,
            link_top: 1830,
            link_size: 42,
            stat_letter_spacing: 1.5,
        },
        (_, "jp") => LayoutStyle {
            base_font_family: "'ygo-jp', 'Yu Gothic', sans-serif",
            name_font_family: "'ygo-jp', 'Yu Gothic', sans-serif",
            type_font_family: "'ygo-jp', 'Yu Gothic', sans-serif",
            effect_font_family: "'ygo-jp', 'Yu Gothic', sans-serif",
            stat_font_family: "'ygo-atk-def', 'Times New Roman', serif",
            link_font_family: "'ygo-link', 'ygo-atk-def', 'Times New Roman', serif",
            password_font_family: "'ygo-password', 'ygo-jp', monospace",
            name_top: 98,
            name_size: 108,
            type_top: 253,
            type_size: 80,
            effect_top: 1528,
            effect_size: 46,
            effect_line_height: 1.17,
            description_size: 38,
            description_line_height: 1.17,
            pendulum_description_top: 1288,
            pendulum_description_size: 36,
            title_max_width_with_attribute: 1033,
            title_max_width_without_attribute: 1161,
            body_max_width: 1175,
            title_letter_spacing: 0.0,
            type_letter_spacing: 0.0,
            effect_letter_spacing: 0.0,
            description_letter_spacing: 0.0,
            name_x: 124,
            effect_x: 122,
            stat_atk_x: 1034,
            stat_def_x: 1310,
            stat_link_x: 1290,
            stat_top: 1818,
            stat_size: 58,
            link_top: 1830,
            link_size: 42,
            stat_letter_spacing: 1.5,
        },
        _ => LayoutStyle {
            base_font_family: "'ygo-sc', 'Microsoft YaHei', sans-serif",
            name_font_family: "'ygo-sc', 'Microsoft YaHei', sans-serif",
            type_font_family: "'ygo-sc', 'Microsoft YaHei', sans-serif",
            effect_font_family: "'ygo-sc', 'Microsoft YaHei', sans-serif",
            stat_font_family: "'ygo-atk-def', 'Times New Roman', serif",
            link_font_family: "'ygo-link', 'ygo-atk-def', 'Times New Roman', serif",
            password_font_family: "'ygo-password', 'ygo-sc', monospace",
            name_top: 111,
            name_size: 94,
            type_top: 254,
            type_size: 76,
            effect_top: 1542,
            effect_size: 40,
            effect_line_height: 1.2,
            description_size: 36,
            description_line_height: 1.2,
            pendulum_description_top: 1282,
            pendulum_description_size: 36,
            title_max_width_with_attribute: 1033,
            title_max_width_without_attribute: 1161,
            body_max_width: 1175,
            title_letter_spacing: 2.0,
            type_letter_spacing: 2.0,
            effect_letter_spacing: 2.0,
            description_letter_spacing: 2.0,
            name_x: 126,
            effect_x: 126,
            stat_atk_x: 1028,
            stat_def_x: 1306,
            stat_link_x: 1294,
            stat_top: 1804,
            stat_size: 54,
            link_top: 1820,
            link_size: 42,
            stat_letter_spacing: 1.5,
        },
    }
}
